version: 1
  pullRequestReviews:
    authentication:
      url: https://audioeye.com
      password: PASSWORD
      formSelector: form
      passwordSelector: input[type=password]
      required: true
